import sys
import io
import os
from langchain_experimental.utilities import PythonREPL

# This executor runs the Python code generated by the agent.
# It captures the logs and keeps things organized in the research_outputs folder.
class CodeExecutor:
    def __init__(self, data_dir="research_outputs"):
        self.repl = PythonREPL()
        self.data_dir = data_dir
        if not os.path.exists(data_dir):
            os.makedirs(data_dir)

    def run(self, code: str):
        # We inject a header so the agent code knows where to save files.
        header = f"""
import pandas as pd
import matplotlib.pyplot as plt
import os

# Base directory for saving files
DATA_DIR = "{self.data_dir}"
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

"""
        full_code = header + code
        
        # Capture standard output so we can see what the code printed.
        old_stdout = sys.stdout
        new_stdout = io.StringIO()
        sys.stdout = new_stdout
        
        try:
            # Running the code in the REPL context.
            result = self.repl.run(full_code)
            sys.stdout = old_stdout
            return {
                "success": True,
                "output": result,
                "logs": new_stdout.getvalue()
            }
        except Exception as e:
            sys.stdout = old_stdout
            return {
                "success": False,
                "error": str(e),
                "logs": new_stdout.getvalue()
            }

def execute_python_code(code: str):
    executor = CodeExecutor()
    return executor.run(code)
